### ISSUE TITLE
examples/southpark-search index error

### ISSUE THREAD

**Issue by Kavan72** [jina-ai/examples#105] opened 2020-07-20 06:09 UTC
- all config file are default
- index function
```
def index():
    data_path = os.path.join(os.environ['DATA_DIR'], os.environ['DATA_FILE'])
    f = Flow().load_config('flow-index.yml')
    data_path_df = pd.read_csv(data_path)
    with f:
        f.index_lines(lines=list(data_path_df['file_data']), batch_size=32)
```
- num docs = `~130000`
- full error (https://pastebin.com/2tAAyc2H)

**Comment by YueLiu-jina** [comment] 2020-07-20 10:59
Hi @Kavan72 ,

Thank you for your interest in Jina! 

The problem is that the num docs you chose was too big. As written in our tutorial, we have 106,820 lines of data, so 130,000 will cause an out-of-range problem. We will add range check feature later on to avoid this kind of problem.

For now, could you please retry with a smaller num-docs, i.e. less than 106,820.

**Comment by Kavan72** [comment] 2020-07-20 11:19
i tried with 2800 files but still same error.

**Comment by YueLiu-jina** [comment] 2020-07-20 13:21
That's so weird. `python app.py -t index -n 2800` does not show any error here on me. What command did you use?

**Comment by Kavan72** [comment] 2020-07-20 21:44
same `python app.py -t index -n 2800`

**Comment by Kavan72** [comment] 2020-07-22 13:43
here is some more info and also the dataset 

- jina version 0.4.1
- transformers version 3.0.2
- torch version 1.5.1

dataset link http://www.filedropper.com/clean-wiki-corpus

**Comment by Kavan72** [comment] 2020-07-23 06:00
@YueLiu-jina can please check with this dataset ?

**Comment by YueLiu-jina** [comment] 2020-07-23 07:57
@Kavan72 I still can not figure out your problem. Everything works fine here with me.

Could you please delete the workspace(`rm -rf /tmp/jina/southpark`), and start over? I'm not sure but maybe this will help.

**Comment by Kavan72** [comment] 2020-07-23 08:31
@YueLiu-jina 
for southpark's data is woking for me but on my dataset i'm getting same error.
[clean-wiki-corpus.txt](https://github.com/jina-ai/examples/files/4964644/clean-wiki-corpus.txt) here is my dataset file. can you please test on this dataset ?

**Comment by JoanFM** [comment] 2020-07-23 08:53
Hello @Kavan72 ,

Apparently in https://github.com/jina-ai/jina/issues/689 they had similar issues: 

Have you checked this?

_The **south-park-example** loads a file where every line is of the form **character[SEP]text**. Then it splits the sentence and extracts the text as a document. Have you made any changes to the **extractor**? Are you concatenating these files one after the other?_

**Comment by Kavan72** [comment] 2020-07-23 08:58
yes i did changes in extractor file for not to split

**Comment by YueLiu-jina** [comment] 2020-07-23 09:34
The indexing does not give any error to me. I changed three places of code, the print_topk function in app.py, the filename in main function, and pods/text_loader.py.

**Comment by Kavan72** [comment] 2020-07-23 09:46
can you tell me what you changed in `pods/text loader.py` ?

**Comment by YueLiu-jina** [comment] 2020-07-23 09:50
```
class TextExtractor(BaseDocCrafter):
    def craft(self, text: str, *args, **kwargs) -> Dict:
        return dict(weight=1., text=text, meta_info=text.encode('utf8'))
```
As Joan said, the southpark treated data as *character[SEP]text*, I just take the whole line as one document. It depends on how you would like to treat your data

**Comment by Kavan72** [comment] 2020-07-27 15:07
@YueLiu-jina 
There is some problem in transformers develop branch.i was using github code when i use old code from pip it's work.
And for other question. is there a way to increase nums of docs in jina (more than 106,820) or work with more nums of docs than 106,820 ?

**Comment by ursachi** [comment] 2020-07-28 08:54
Hi everyone,

I am new to Jina, hence I would like to understand better this limitation of the number of docs. Mz understanding is that the limitation to 106,820 is used for the indexer. What if I have a couple of million of files that I want to index and the number of files is permanently increasing? Should I then create separate doc_indexers (doc_indexer1, doc_indexer2) and have them added in parallel in the flow_index once new files are created? 

If this would be doable, has it any impact on the ranker? Should the ranker be added after a doc_indexer join or how would that work?  

Thanks!

**Comment by JoanFM** [comment] 2020-07-28 09:27
Hi @Kavan72 ,

106820 is currently the number of lines that the file **character-lines.csv** has, it is not a limitation of **jina**. So if you provide a file with the same structure but with more lines, they will all be indexed as wel.

I hope it helps.

**Comment by Kavan72** [comment] 2020-07-28 13:05
@JoanFM i did same.
- create same structure dataset 
- run index 

num of lines in text file = `~130000`
full error (https://pastebin.com/FpEL0ErH)

**Comment by JoanFM** [comment] 2020-07-28 15:43
Hey @Kavan72 ,

Did you first manage to get the 106820 documents from South-park indexed? From the information of the error is hard to tell what is the error. It seems like a **KeyBoardInterrupt** event killed a pod. Apparently your flow fails to index document number around 2300.

Anyway, examples are not yet guaranteed to work with jina version 0.4.1, could you try using jina 0.3.8 until migration of examples has been completed?

**Comment by Kavan72** [comment] 2020-07-31 06:45
@JoanFM 
I'm getting same error on jina 0.3.8 also. so what i did basically, i divided my corpus into 10 parts (10,000 each). After started run indexing on each small corpus to find which corpus is throwing error. so here is dataset which is throwing error and also i'm providing my all lib version

Dataset file 10,000 line:- [small-corpus.zip](https://github.com/jina-ai/examples/files/5005509/100-batch-clean-corpus.zip)
Python version:- 3.7.8
All libs version info:- https://pastebin.com/aaWgLiVj

**Comment by JoanFM** [comment] 2020-07-31 07:04
Hey @Kavan72 

Can you tell me how you process the data exactly? I guess you are not using the same executors as the example right? The [SEP] does not exist. Is the only change the suggestion from @YueLiu-jina? 

Thanks

**Comment by Kavan72** [comment] 2020-07-31 07:54
@JoanFM 
yes i'm not separating data with `[SEP]`. i need data as it is, so i'm taking whole line as one document.

**Comment by JoanFM** [comment] 2020-08-01 10:13
Hey @Kavan72 ; I could not reproduce the issue; can u give a full log of the error?

**Comment by Kavan72** [comment] 2020-08-01 12:35
@JoanFM 
[jina_full_error.txt](https://github.com/jina-ai/examples/files/5010353/jina_full_error.txt)
here is the full error log 

step for reproduce this issue
- clone southpark-search example.
- edit three file (`print_topk function in app.py, the filename in main function, and pods/text_loader.py).
  -  `print_topk` function in app.py.
  -  `filename` in main function (file app.py).
  -  `pods/text_loader.py` for not to split with `[SEP]` (take whole line as one document).

**Comment by JoanFM** [comment] 2020-08-02 07:48
Hey @Kavan72.

I think that the error you are seeing is not a functional error but a problem of resources. 

Is it possible that when the error happens you can observe a really large memory usage?

**Comment by Kavan72** [comment] 2020-08-03 04:53
@JoanFM i didn't notice that but i was running with 32GB RAM. So, do i have more ram or it's enough?

**Comment by JoanFM** [comment] 2020-08-03 06:09
Hey @Kavan72, 

It should be more than enough. 

Reference that may help investigate the issue:
https://github.com/grpc/grpc/issues/13544

**Comment by JoanFM** [comment] 2020-08-03 21:12
Hey @Kavan72.

It seems like a tricky situation that I do not manage to reproduce. Apparently the request somehow seems not to be generated properly. 

Does the error always occur when processing the same document number? Or the same batch?

**Comment by Kavan72** [comment] 2020-08-04 05:40
@JoanFM 
grpc/grpc#13544 i dont this so this one help us for investigate this issue.
yes, it's stop on same batch, batch 3304 on this dataset.

**Comment by JoanFM** [comment] 2020-08-04 05:46
> @JoanFM
> [grpc/grpc#13544](https://github.com/grpc/grpc/issues/13544) i dont this so this one help us for investigate this issue.
> yes, it's stop on same batch, batch 3304 on this dataset.

Is it constantly so?

**Comment by Kavan72** [comment] 2020-08-04 06:00
yes, i tried on my laptop and also on ubuntu server 18.04 and 20.04.

**Comment by JoanFM** [comment] 2020-08-04 06:36
Hey @Kavan72 , I am really sorry that I am not being of much help here.

I am trying many things and do not manage to make it crash.

Can you maybe isolate in a new file from line 3296 to 3312. And then add some print lines into `jina/clients/python/requests.py` inside the `_generator` method and print the generated `request`?

In theory it seems to be failing because no valid iterator is passed from this method. Maybe this can help to isolate the issue.

Thanks for your patience and collaboration

**Comment by Kavan72** [comment] 2020-08-04 07:10
@JoanFM 
I'm happy for you are helping me :)
I'm trying your approach

**Comment by Kavan72** [comment] 2020-08-06 10:52
@JoanFM 
after too many debugging i found which file is throwing error and why 
here is the file [small-dataset.csv.txt](https://github.com/jina-ai/examples/files/5034333/small-dataset.csv.txt)
problem is file_data is starting with url or contain url (i guess it not a issue). if you remove this url than no error

**Comment by JoanFM** [comment] 2020-08-06 10:59
Hey @Kavan72 ,

Great news! Can you tell me in which line it is having the problem? Or was it in your custom loader?

**Comment by Kavan72** [comment] 2020-08-06 11:01
custom loader
```
class TextExtractor(BaseDocCrafter):
    def craft(self, text: str, *args, **kwargs) -> Dict:
        return dict(weight=1., text=text, meta_info=text.encode('utf8'))
```

**Comment by JoanFM** [comment] 2020-08-06 11:03
So I guess you can now handle there the `exception` and run your indexing pipeline right?

**Comment by Kavan72** [comment] 2020-08-06 11:07
only if i remove url from doc. I dont know another way

**Comment by JoanFM** [comment] 2020-08-06 11:09
can't u catch what happens to the `meta_info` encoder? it seems to be the reason

**Comment by Kavan72** [comment] 2020-08-06 16:01
@JoanFM 
Here is full traceback:- https://pastebin.com/a9nJbgXx
Problem is here https://github.com/jina-ai/jina/blob/83bc04e9af2c707b327564140394ba923b95c39c/jina/clients/python/request.py#L65
If you pass the raw data still is consider as a http

**Comment by JoanFM** [comment] 2020-08-06 16:37
> @JoanFM
> Here is full traceback:- https://pastebin.com/a9nJbgXx
> Problem is here https://github.com/jina-ai/jina/blob/83bc04e9af2c707b327564140394ba923b95c39c/jina/clients/python/request.py#L65
> If you pass the raw data still is consider as a http

Oh, great catch!

I still do not understand why I could not reproduce, but it seems like an issue, maybe we should `fallback` to consider it as text if the url parsing is not successful.

Can you create an `issue` on the `jina` repo with the details of the problem and the indication of where in the code the issue is found? 

Then if you have a solution in mind, feel free to provide a Pull Request to fix it! 

Thank you very much!

**Comment by Kavan72** [comment] 2020-08-06 18:40
@JoanFM 
https://github.com/jina-ai/jina/issues/776

**Comment by JoanFM** [comment] 2020-08-07 10:52
Hi @Kavan72, thank you very much for your patience and effort. Closing the issue ...

**Closed by JoanFM** 2020-08-07 10:52 UTC
