### ISSUE TITLE
Issues with new faiss search example

### ISSUE THREAD

**Issue by ivana-bt** [jina-ai/examples#320] opened 2020-12-16 14:05 UTC
Hi,

I just found the (WIP) PR for a new faiss search implementation, thanks for adding this :+1: 

I'm using latest `240b03067092b5379a62ff591e05afa94fd95beb` of Jina and I got two problems with that new faiss search example:

It seems that the `match` object attributes have changed:

https://github.com/jina-ai/examples/blob/91f95ad5f0719d6b08a8f029b0bea0a6649afea0/faiss-search/app.py#L50

is no longer working, so `match.blob.dense` has to be used now, instead of `match.blob`:

```python
m_fn = np.frombuffer(match.blob.dense.buffer, match.blob.dense.dtype)
```

That is working in my case with latest Jina version.

The second problem that I found: 

The groundtruth data returns a tensor of ids (integer!) that are compared in the `recall_at_k` function:

https://github.com/jina-ai/examples/blob/91f95ad5f0719d6b08a8f029b0bea0a6649afea0/faiss-search/app.py#L63-L72

But the top k alternative matches (`results`) no longer return integer ids. Instead, a tensor of strings with hashes is returned, e.g:

```python
['607193efc5b02b0a' 'a205836af2cfe99d' '054bd0959263562a'
  '8f8ace76ded7f6cb' 'd9f5ecb512f330b0']]
```

I wasn't able to fix that after inspecting the `match` object.

Help is much appreciated :hugs:

**Comment by JoanFM** [comment] 2020-12-16 14:24
> Hi,
> 
> I just found the (WIP) PR for a new faiss search implementation, thanks for adding this 
> 
> I'm using latest `240b03067092b5379a62ff591e05afa94fd95beb` of Jina and I got two problems with that new faiss search example:
> 
> It seems that the `match` object attributes have changed:
> 
> https://github.com/jina-ai/examples/blob/91f95ad5f0719d6b08a8f029b0bea0a6649afea0/faiss-search/app.py#L50
> 
> is no longer working, so `match.blob.dense` has to be used now, instead of `match.blob`:
> 
> ```python
> m_fn = np.frombuffer(match.blob.dense.buffer, match.blob.dense.dtype)
> ```
> 
> That is working in my case with latest Jina version.
> 
> The second problem that I found:
> 
> The groundtruth data returns a tensor of ids (integer!) that are compared in the `recall_at_k` function:
> 
> https://github.com/jina-ai/examples/blob/91f95ad5f0719d6b08a8f029b0bea0a6649afea0/faiss-search/app.py#L63-L72
> 
> But the top k alternative matches (`results`) no longer return integer ids. Instead, a tensor of strings with hashes is returned, e.g:
> 
> ```python
> ['607193efc5b02b0a' 'a205836af2cfe99d' '054bd0959263562a'
>   '8f8ace76ded7f6cb' 'd9f5ecb512f330b0']]
> ```
> 
> I wasn't able to fix that after inspecting the `match` object.
> 
> Help is much appreciated

Hey @ivana-bt ,

The problem is that the example is very old and the branch still did not manage to have the example working and see the problem. However, the way evaluation was done in this example is not valid anymore because document IDs have been heavily refactored.

However, since Jina provides Evaluators as new family of Executors, the way this evaluation works will drastically change. 

Sorry for the inconvinience

**Comment by JoanFM** [comment] 2021-01-09 09:20
Hey @ivana-bt ,

There is a PR that is about to be merged and which enables this example again with new jina version

**Comment by JoanFM** [comment] 2021-01-09 09:21
The example shows how to use Evaluation in jina using the Evaluation Executors.

**Comment by JoanFM** [comment] 2021-01-14 10:46
Closing since example update

**Closed by JoanFM** 2021-01-14 10:46 UTC
